### ISSUE TITLE
Convert the mapping files to CSV/TSV

### ISSUE THREAD

**Issue by clarkevans** [TuftsCTSI/N3C#18]
If it's not too much a bother, it'd be far more useful if the mappings files were to be committed as CSV/TSV format. This will permit them to be used directly by automated programs without converting from Excel first. This means each tab may be a separate file within a given directory. It will also let Git do "diff" for you and also let GitHub provide a lovely viewer.

**Comment by martyalvarez** [comment]
Hi Clark - I reviewed and merged these so that I could link them to the N3C report due tomorrow.
I don't know how to do what you are asking, however I'm happy to watch you do this when you are available. LMK! -marty

**Comment by p-talapova** [comment]
Hi @clarkevans. The uploaded XLSX file is intentionally provided to demonstrate interim accomplishments in a human-readable lookup table format. The results are voluminous and promising, but not entirely satisfying, that is why I do not recommend using them officially in ETLs. 
However, I respect your request, and I will be able to add a CSV file via a new pull request on 06/23.

**Comment by clarkevans** [comment]
Polina,  Perhaps it was an error to suggest this. We could revert and close this issue. - Clark

**Comment by clarkevans** [comment]
I reverted this. It was a misguided request. Thank you so much. My apologies.
